- hosts: all
  tasks:
          - name: Docker repository
            yum_repository:
                 description: "repo for docker"
                 name: "docker-ce"
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                 gpgcheck: false

          - name: Installing Docker Software
            package:
                 name: "docker-ce-18.09.1-3.el7.x86_64"
                 state: present

          - name: starting docker service
            service:
                 name: docker
                 state: started
          - pip:
                  name: docker-py

          - name: Pulling the HTTPD docker image
            docker_image:
                    name: httpd
                    source: pull

          - name: Copying file into home
            copy:
                    src: web.html
                    dest: /task

          - name: creating a docker container for webserver
            community.general.docker_container:
                    name: container1
                    image: httpd
                    exposed_ports: "81"
                    ports: "7000:81"
                    state: started
                    detach: yes
                    volumes: /task:/usr/local/apache2/htdocs/

